# Generated by Django 3.2.25 on 2026-07-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('expired', '已过期')], default='approved', max_length=20, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
